export default [
  { uri: "https://i.imgur.com/wxqlQkh.jpg" },
  { uri: "https://i.imgur.com/G2Whuq3.jpg" },
  { uri: "https://i.imgur.com/0bUSEBX.jpg" },
  { uri: "https://i.imgur.com/giP58XN.jpg" },
  { uri: "https://i.imgur.com/iKdXwVm.jpg" },
  { uri: "https://i.imgur.com/IvpoR40.jpg" },
  { uri: "https://i.imgur.com/zJIxPEo.jpg" },
  { uri: "https://i.imgur.com/CKlmtPs.jpg" },
  { uri: "https://i.imgur.com/fnMylHI.jpg" },
  { uri: "https://i.imgur.com/vGXYiYy.jpg" },
  { uri: "https://i.imgur.com/MnOB9Le.jpg" },
  { uri: "https://i.imgur.com/YqsZKgc.jpg" },
  { uri: "https://i.imgur.com/0BJobQo.jpg" },
  { uri: "https://i.imgur.com/Otbz312.jpg" },
];
