// This file is generated. DO NOT MODIFY
import hellogl_E from "./hellogl";
import * as hellogl_m from "./hellogl/meta";
export const hellogl = { Main: hellogl_E, ...hellogl_m };
import helloblue_E from "./helloblue";
import * as helloblue_m from "./helloblue/meta";
export const helloblue = { Main: helloblue_E, ...helloblue_m };
import helloblueanim_E from "./helloblueanim";
import * as helloblueanim_m from "./helloblueanim/meta";
export const helloblueanim = { Main: helloblueanim_E, ...helloblueanim_m };
import colordisc_E from "./colordisc";
import * as colordisc_m from "./colordisc/meta";
export const colordisc = { Main: colordisc_E, ...colordisc_m };
import gradients_E from "./gradients";
import * as gradients_m from "./gradients/meta";
export const gradients = { Main: gradients_E, ...gradients_m };
import diamondcrop_E from "./diamondcrop";
import * as diamondcrop_m from "./diamondcrop/meta";
export const diamondcrop = { Main: diamondcrop_E, ...diamondcrop_m };
import diamondhello_E from "./diamondhello";
import * as diamondhello_m from "./diamondhello/meta";
export const diamondhello = { Main: diamondhello_E, ...diamondhello_m };
import diamondanim_E from "./diamondanim";
import * as diamondanim_m from "./diamondanim/meta";
export const diamondanim = { Main: diamondanim_E, ...diamondanim_m };
import heart_E from "./heart";
import * as heart_m from "./heart/meta";
export const heart = { Main: heart_E, ...heart_m };
import hearts_E from "./hearts";
import * as hearts_m from "./hearts/meta";
export const hearts = { Main: hearts_E, ...hearts_m };
import animated_E from "./animated";
import * as animated_m from "./animated/meta";
export const animated = { Main: animated_E, ...animated_m };
import saturation_E from "./saturation";
import * as saturation_m from "./saturation/meta";
export const saturation = { Main: saturation_E, ...saturation_m };
import colorscale_E from "./colorscale";
import * as colorscale_m from "./colorscale/meta";
export const colorscale = { Main: colorscale_E, ...colorscale_m };
import distortion_E from "./distortion";
import * as distortion_m from "./distortion/meta";
export const distortion = { Main: distortion_E, ...distortion_m };
import transitions_E from "./transitions";
import * as transitions_m from "./transitions/meta";
export const transitions = { Main: transitions_E, ...transitions_m };
import glsledit_E from "./glsledit";
import * as glsledit_m from "./glsledit/meta";
export const glsledit = { Main: glsledit_E, ...glsledit_m };
import paint_E from "./paint";
import * as paint_m from "./paint/meta";
export const paint = { Main: paint_E, ...paint_m };
import pixeleditor_E from "./pixeleditor";
import * as pixeleditor_m from "./pixeleditor/meta";
export const pixeleditor = { Main: pixeleditor_E, ...pixeleditor_m };
import blurxy_E from "./blurxy";
import * as blurxy_m from "./blurxy/meta";
export const blurxy = { Main: blurxy_E, ...blurxy_m };
import blurxydownscale_E from "./blurxydownscale";
import * as blurxydownscale_m from "./blurxydownscale/meta";
export const blurxydownscale = {
  Main: blurxydownscale_E,
  ...blurxydownscale_m,
};
import blurmulti_E from "./blurmulti";
import * as blurmulti_m from "./blurmulti/meta";
export const blurmulti = { Main: blurmulti_E, ...blurmulti_m };
import blurmap_E from "./blurmap";
import * as blurmap_m from "./blurmap/meta";
export const blurmap = { Main: blurmap_E, ...blurmap_m };
import blurmapmouse_E from "./blurmapmouse";
import * as blurmapmouse_m from "./blurmapmouse/meta";
export const blurmapmouse = { Main: blurmapmouse_E, ...blurmapmouse_m };
import blurmapdyn_E from "./blurmapdyn";
import * as blurmapdyn_m from "./blurmapdyn/meta";
export const blurmapdyn = { Main: blurmapdyn_E, ...blurmapdyn_m };
import blurfeedback_E from "./blurfeedback";
import * as blurfeedback_m from "./blurfeedback/meta";
export const blurfeedback = { Main: blurfeedback_E, ...blurfeedback_m };
import gol_E from "./gol";
import * as gol_m from "./gol/meta";
export const gol = { Main: gol_E, ...gol_m };
import golglider_E from "./golglider";
import * as golglider_m from "./golglider/meta";
export const golglider = { Main: golglider_E, ...golglider_m };
import golrot_E from "./golrot";
import * as golrot_m from "./golrot/meta";
export const golrot = { Main: golrot_E, ...golrot_m };
import golrotscu_E from "./golrotscu";
import * as golrotscu_m from "./golrotscu/meta";
export const golrotscu = { Main: golrotscu_E, ...golrotscu_m };
import camera_E from "./camera";
import * as camera_m from "./camera/meta";
export const camera = { Main: camera_E, ...camera_m };
import mergechannels_E from "./mergechannels";
import * as mergechannels_m from "./mergechannels/meta";
export const mergechannels = { Main: mergechannels_E, ...mergechannels_m };
import sdf1_E from "./sdf1";
import * as sdf1_m from "./sdf1/meta";
export const sdf1 = { Main: sdf1_E, ...sdf1_m };
import demotunnel_E from "./demotunnel";
import * as demotunnel_m from "./demotunnel/meta";
export const demotunnel = { Main: demotunnel_E, ...demotunnel_m };
import demodesert_E from "./demodesert";
import * as demodesert_m from "./demodesert/meta";
export const demodesert = { Main: demodesert_E, ...demodesert_m };
import demodesertcrt_E from "./demodesertcrt";
import * as demodesertcrt_m from "./demodesertcrt/meta";
export const demodesertcrt = { Main: demodesertcrt_E, ...demodesertcrt_m };
import ibex_E from "./ibex";
import * as ibex_m from "./ibex/meta";
export const ibex = { Main: ibex_E, ...ibex_m };
import three_E from "./three";
import * as three_m from "./three/meta";
export const three = { Main: three_E, ...three_m };
