import hellogl_E from './hellogl';
import * as hellogl_m from './hellogl/meta';
import hellogl_s from '!raw!./hellogl/index.js';
export const hellogl={ Example: hellogl_E, source: hellogl_s, ...hellogl_m };
import helloblue_E from './helloblue';
import * as helloblue_m from './helloblue/meta';
import helloblue_s from '!raw!./helloblue/index.js';
export const helloblue={ Example: helloblue_E, source: helloblue_s, ...helloblue_m };
import helloblueanim_E from './helloblueanim';
import * as helloblueanim_m from './helloblueanim/meta';
import helloblueanim_s from '!raw!./helloblueanim/index.js';
export const helloblueanim={ Example: helloblueanim_E, source: helloblueanim_s, ...helloblueanim_m };
import colordisc_E from './colordisc';
import * as colordisc_m from './colordisc/meta';
import colordisc_s from '!raw!./colordisc/index.js';
export const colordisc={ Example: colordisc_E, source: colordisc_s, ...colordisc_m };
import gradients_E from './gradients';
import * as gradients_m from './gradients/meta';
import gradients_s from '!raw!./gradients/index.js';
export const gradients={ Example: gradients_E, source: gradients_s, ...gradients_m };
import diamondcrop_E from './diamondcrop';
import * as diamondcrop_m from './diamondcrop/meta';
import diamondcrop_s from '!raw!./diamondcrop/index.js';
export const diamondcrop={ Example: diamondcrop_E, source: diamondcrop_s, ...diamondcrop_m };
import diamondhello_E from './diamondhello';
import * as diamondhello_m from './diamondhello/meta';
import diamondhello_s from '!raw!./diamondhello/index.js';
export const diamondhello={ Example: diamondhello_E, source: diamondhello_s, ...diamondhello_m };
import diamondanim_E from './diamondanim';
import * as diamondanim_m from './diamondanim/meta';
import diamondanim_s from '!raw!./diamondanim/index.js';
export const diamondanim={ Example: diamondanim_E, source: diamondanim_s, ...diamondanim_m };
import heart_E from './heart';
import * as heart_m from './heart/meta';
import heart_s from '!raw!./heart/index.js';
export const heart={ Example: heart_E, source: heart_s, ...heart_m };
import animated_E from './animated';
import * as animated_m from './animated/meta';
import animated_s from '!raw!./animated/index.js';
export const animated={ Example: animated_E, source: animated_s, ...animated_m };
import saturation_E from './saturation';
import * as saturation_m from './saturation/meta';
import saturation_s from '!raw!./saturation/index.js';
export const saturation={ Example: saturation_E, source: saturation_s, ...saturation_m };
import colorscale_E from './colorscale';
import * as colorscale_m from './colorscale/meta';
import colorscale_s from '!raw!./colorscale/index.js';
export const colorscale={ Example: colorscale_E, source: colorscale_s, ...colorscale_m };
import distortion_E from './distortion';
import * as distortion_m from './distortion/meta';
import distortion_s from '!raw!./distortion/index.js';
export const distortion={ Example: distortion_E, source: distortion_s, ...distortion_m };
import transitions_E from './transitions';
import * as transitions_m from './transitions/meta';
import transitions_s from '!raw!./transitions/index.js';
export const transitions={ Example: transitions_E, source: transitions_s, ...transitions_m };
import textfunky_E from './textfunky';
import * as textfunky_m from './textfunky/meta';
import textfunky_s from '!raw!./textfunky/index.js';
export const textfunky={ Example: textfunky_E, source: textfunky_s, ...textfunky_m };
import textanimated_E from './textanimated';
import * as textanimated_m from './textanimated/meta';
import textanimated_s from '!raw!./textanimated/index.js';
export const textanimated={ Example: textanimated_E, source: textanimated_s, ...textanimated_m };
import glsledit_E from './glsledit';
import * as glsledit_m from './glsledit/meta';
import glsledit_s from '!raw!./glsledit/index.js';
export const glsledit={ Example: glsledit_E, source: glsledit_s, ...glsledit_m };
import paint_E from './paint';
import * as paint_m from './paint/meta';
import paint_s from '!raw!./paint/index.js';
export const paint={ Example: paint_E, source: paint_s, ...paint_m };
import pixeleditor_E from './pixeleditor';
import * as pixeleditor_m from './pixeleditor/meta';
import pixeleditor_s from '!raw!./pixeleditor/index.js';
export const pixeleditor={ Example: pixeleditor_E, source: pixeleditor_s, ...pixeleditor_m };
import blurxy_E from './blurxy';
import * as blurxy_m from './blurxy/meta';
import blurxy_s from '!raw!./blurxy/index.js';
export const blurxy={ Example: blurxy_E, source: blurxy_s, ...blurxy_m };
import blurxydownscale_E from './blurxydownscale';
import * as blurxydownscale_m from './blurxydownscale/meta';
import blurxydownscale_s from '!raw!./blurxydownscale/index.js';
export const blurxydownscale={ Example: blurxydownscale_E, source: blurxydownscale_s, ...blurxydownscale_m };
import blurmulti_E from './blurmulti';
import * as blurmulti_m from './blurmulti/meta';
import blurmulti_s from '!raw!./blurmulti/index.js';
export const blurmulti={ Example: blurmulti_E, source: blurmulti_s, ...blurmulti_m };
import blurmap_E from './blurmap';
import * as blurmap_m from './blurmap/meta';
import blurmap_s from '!raw!./blurmap/index.js';
export const blurmap={ Example: blurmap_E, source: blurmap_s, ...blurmap_m };
import blurmapmouse_E from './blurmapmouse';
import * as blurmapmouse_m from './blurmapmouse/meta';
import blurmapmouse_s from '!raw!./blurmapmouse/index.js';
export const blurmapmouse={ Example: blurmapmouse_E, source: blurmapmouse_s, ...blurmapmouse_m };
import blurmapdyn_E from './blurmapdyn';
import * as blurmapdyn_m from './blurmapdyn/meta';
import blurmapdyn_s from '!raw!./blurmapdyn/index.js';
export const blurmapdyn={ Example: blurmapdyn_E, source: blurmapdyn_s, ...blurmapdyn_m };
import blurimgtitle_E from './blurimgtitle';
import * as blurimgtitle_m from './blurimgtitle/meta';
import blurimgtitle_s from '!raw!./blurimgtitle/index.js';
export const blurimgtitle={ Example: blurimgtitle_E, source: blurimgtitle_s, ...blurimgtitle_m };
import gol_E from './gol';
import * as gol_m from './gol/meta';
import gol_s from '!raw!./gol/index.js';
export const gol={ Example: gol_E, source: gol_s, ...gol_m };
import golglider_E from './golglider';
import * as golglider_m from './golglider/meta';
import golglider_s from '!raw!./golglider/index.js';
export const golglider={ Example: golglider_E, source: golglider_s, ...golglider_m };
import golrot_E from './golrot';
import * as golrot_m from './golrot/meta';
import golrot_s from '!raw!./golrot/index.js';
export const golrot={ Example: golrot_E, source: golrot_s, ...golrot_m };
import golrotscu_E from './golrotscu';
import * as golrotscu_m from './golrotscu/meta';
import golrotscu_s from '!raw!./golrotscu/index.js';
export const golrotscu={ Example: golrotscu_E, source: golrotscu_s, ...golrotscu_m };
import video_E from './video';
import * as video_m from './video/meta';
import video_s from '!raw!./video/index.js';
export const video={ Example: video_E, source: video_s, ...video_m };
import blurvideo_E from './blurvideo';
import * as blurvideo_m from './blurvideo/meta';
import blurvideo_s from '!raw!./blurvideo/index.js';
export const blurvideo={ Example: blurvideo_E, source: blurvideo_s, ...blurvideo_m };
import webcam_E from './webcam';
import * as webcam_m from './webcam/meta';
import webcam_s from '!raw!./webcam/index.js';
export const webcam={ Example: webcam_E, source: webcam_s, ...webcam_m };
import webcampersistence_E from './webcampersistence';
import * as webcampersistence_m from './webcampersistence/meta';
import webcampersistence_s from '!raw!./webcampersistence/index.js';
export const webcampersistence={ Example: webcampersistence_E, source: webcampersistence_s, ...webcampersistence_m };
import golwebcam_E from './golwebcam';
import * as golwebcam_m from './golwebcam/meta';
import golwebcam_s from '!raw!./golwebcam/index.js';
export const golwebcam={ Example: golwebcam_E, source: golwebcam_s, ...golwebcam_m };
import mergechannels_E from './mergechannels';
import * as mergechannels_m from './mergechannels/meta';
import mergechannels_s from '!raw!./mergechannels/index.js';
export const mergechannels={ Example: mergechannels_E, source: mergechannels_s, ...mergechannels_m };
import mergechannelsfun_E from './mergechannelsfun';
import * as mergechannelsfun_m from './mergechannelsfun/meta';
import mergechannelsfun_s from '!raw!./mergechannelsfun/index.js';
export const mergechannelsfun={ Example: mergechannelsfun_E, source: mergechannelsfun_s, ...mergechannelsfun_m };
import demotunnel_E from './demotunnel';
import * as demotunnel_m from './demotunnel/meta';
import demotunnel_s from '!raw!./demotunnel/index.js';
export const demotunnel={ Example: demotunnel_E, source: demotunnel_s, ...demotunnel_m };
import demodesert_E from './demodesert';
import * as demodesert_m from './demodesert/meta';
import demodesert_s from '!raw!./demodesert/index.js';
export const demodesert={ Example: demodesert_E, source: demodesert_s, ...demodesert_m };
import demodesertcrt_E from './demodesertcrt';
import * as demodesertcrt_m from './demodesertcrt/meta';
import demodesertcrt_s from '!raw!./demodesertcrt/index.js';
export const demodesertcrt={ Example: demodesertcrt_E, source: demodesertcrt_s, ...demodesertcrt_m };
import behindasteroids_E from './behindasteroids';
import * as behindasteroids_m from './behindasteroids/meta';
import behindasteroids_s from '!raw!./behindasteroids/index.js';
export const behindasteroids={ Example: behindasteroids_E, source: behindasteroids_s, ...behindasteroids_m };
import ibex_E from './ibex';
import * as ibex_m from './ibex/meta';
import ibex_s from '!raw!./ibex/index.js';
export const ibex={ Example: ibex_E, source: ibex_s, ...ibex_m };
